SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE LANmonitor;

CREATE TABLE `scan` (
  `IP` varchar(16) NOT NULL,
  `MAC` varchar(37) NOT NULL,
  `MACvendor` varchar(255) NOT NULL,
  `UP` int(1) NOT NULL,
  `HOST` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `temp_scan` (
  `IP` varchar(16) NOT NULL,
  `MAC` varchar(37) NOT NULL,
  `MACvendor` varchar(255) NOT NULL,
  `UP` int(1) NOT NULL,
  `HOST` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `scan`
  ADD PRIMARY KEY (`MAC`) USING BTREE,
  ADD UNIQUE KEY `IP` (`IP`),
  ADD UNIQUE KEY `HOST` (`HOST`);

ALTER TABLE `temp_scan`
  ADD PRIMARY KEY (`MAC`) USING BTREE,
  ADD UNIQUE KEY `IP` (`IP`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
